name: BuildRelease

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build example
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Clean workspace
      run: |
        echo "Cleaning up previous run"
        rm -rf "${{ github.workspace }}/build"

    - name: Checkout pico-sdk/develop
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        ref: master
        path: pico-sdk

    - name: Checkout pico-sdk submodules
      working-directory: ${{github.workspace}}/pico-sdk
      run: git submodule update --init

    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run:  cmake -E make_directory ${{github.workspace}}/build

    - name: GCC 6.2.1 Release
      shell: bash
      working-directory: ./build
      run: cmake ../ -DCMAKE_BUILD_TYPE=Release -DPICO_TOOLCHAIN_PATH=/opt/arm/gcc-arm-none-eabi-6_2-2016q4; make --output-sync=target --no-builtin-rules --no-builtin-variables -j$(nproc)

    - name: Configure CMake
      shell: bash
      working-directory: ./build
      run: PICO_SDK_PATH=${{github.workspace}}/pico-sdk cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Get core count
      id: core_count
      run : cat /proc/cpuinfo  | grep processor | wc -l

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build ${{github.workspace}}/build --config $BUILD_TYPE --parallel $(nproc)
