name: BuildRelease

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build example
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Clean workspace
      run: |
        echo "Cleaning up previous run"
        ls

    - name: Checkout pico-sdk/develop
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        ref: master
        path: pico-sdk

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}}/../ -DCMAKE_BUILD_TYPE=$BUILD_TYPE
