name: Create Release Note
on:
  push:
    branches:
    - sprint/*

permissions:
  contents: write

env:
  BUILD_TYPE: Debug
  TZ: "Asia/Tokyo"
  PROJECT_DIR: "RP2040"

jobs:
  build:
    name: Build Releases on tags
    runs-on: ubuntu-latest

    steps:
    - name: Checkout my project
      uses: actions/checkout@v4

    - name: Read current version
      id: current_version
      run: echo "CURRENT_VERSION=$(cat VERSION)" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.current_version.outputs.CURRENT_VERSION }}
        release_name: Release ${{ steps.current_version.outputs.CURRENT_VERSION }}
        draft: true
        prerelease: false
